import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import pandas as pd

def create_html_email(jobs_df, top_jobs_df):
    """
    Create an HTML email body with job statistics and listings
    """
    total_jobs = len(jobs_df)
    top_jobs_count = len(top_jobs_df)
    current_date = datetime.now().strftime('%B %d, %Y')
    
    html = f"""
    <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                }}
                .header {{
                    background-color: #4CAF50;
                    color: white;
                    padding: 20px;
                    text-align: center;
                }}
                .stats {{
                    background-color: #f4f4f4;
                    padding: 15px;
                    margin: 20px 0;
                    border-radius: 5px;
                }}
                .job-card {{
                    border: 1px solid #ddd;
                    padding: 15px;
                    margin: 10px 0;
                    border-radius: 5px;
                    background-color: #fff;
                }}
                .job-title {{
                    color: #2196F3;
                    font-size: 18px;
                    font-weight: bold;
                    margin-bottom: 5px;
                }}
                .job-company {{
                    color: #666;
                    font-size: 14px;
                }}
                .job-location {{
                    color: #999;
                    font-size: 13px;
                    font-style: italic;
                }}
                .apply-btn {{
                    display: inline-block;
                    padding: 8px 16px;
                    background-color: #4CAF50;
                    color: white;
                    text-decoration: none;
                    border-radius: 4px;
                    margin-top: 10px;
                }}
                .footer {{
                    text-align: center;
                    padding: 20px;
                    color: #999;
                    font-size: 12px;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>Weekly AI Jobs Report</h1>
                <p>{current_date}</p>
            </div>
            
            <div class="stats">
                <h2>This Week's Statistics</h2>
                <ul>
                    <li><strong>Total Jobs Scraped:</strong> {total_jobs}</li>
                    <li><strong>Top AI/ML Positions:</strong> {top_jobs_count}</li>
                    <li><strong>Report Generated:</strong> {current_date}</li>
                </ul>
            </div>
            
            <h2>Top AI Engineering Roles This Week</h2>
    """
    
    # Add job listings
    if not top_jobs_df.empty:
        for idx, job in top_jobs_df.iterrows():
            html += f"""
            <div class="job-card">
                <div class="job-title">{job['title']}</div>
                <div class="job-company">{job['company']}</div>
                <div class="job-location">{job['location']}</div>
                <a href="{job['link']}" class="apply-btn">View Job</a>
            </div>
            """
    else:
        html += "<p>No jobs found matching the criteria this week.</p>"
    
    html += """
            <div class="footer">
                <p>This is an automated weekly report. Generated by your AI Job Tracker.</p>
            </div>
        </body>
    </html>
    """
    
    return html

def create_plain_text_email(jobs_df, top_jobs_df):
    """
    Create a plain text email body
    """
    total_jobs = len(jobs_df)
    top_jobs_count = len(top_jobs_df)
    current_date = datetime.now().strftime('%B %d, %Y')
    
    text = f"""

    WEEKLY AI JOBS REPORT
    {current_date}

    
    THIS WEEK'S STATISTICS:
    - Total Jobs Scraped: {total_jobs}
    - Top AI/ML Positions: {top_jobs_count}
    
    TOP AI ENGINEERING ROLES THIS WEEK:
    
    """
    
    if not top_jobs_df.empty:
        for idx, job in top_jobs_df.iterrows():
            text += f"""
    {idx + 1}. {job['title']}
       Company: {job['company']}
       Location: {job['location']}
       Apply: {job['link']}
    
    """
    else:
        text += "No jobs found matching the criteria this week.\n"
    
    text += """
    This is an automated weekly report.
    Generated by your AI Job Tracker.
    """
    return text

def send_email(sender_email, sender_password, recipient_email, subject, html_body, text_body):
    """
    Send email via Gmail SMTP
    
    Args:
        sender_email: Your Gmail address
        sender_password: Your Gmail app password (not regular password)
        recipient_email: Recipient's email address
        subject: Email subject
        html_body: HTML version of email
        text_body: Plain text version of email
    """
    try:
        # Create message
        message = MIMEMultipart('alternative')
        message['Subject'] = subject
        message['From'] = sender_email
        message['To'] = recipient_email
        
        # Attach both plain text and HTML versions
        part1 = MIMEText(text_body, 'plain')
        part2 = MIMEText(html_body, 'html')
        
        message.attach(part1)
        message.attach(part2)
        
        # Connect to Gmail SMTP server
        print("Connecting to Gmail SMTP server...")
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            print("Logging in...")
            server.login(sender_email, sender_password)
            print("Sending email...")
            server.send_message(message)
            print(f"Email sent successfully to {recipient_email}")
            
        return True
        
    except Exception as e:
        print(f"Error sending email: {e}")
        return False

# Test function
if __name__ == "__main__":
    # Sample data for testing
    sample_jobs = pd.DataFrame({
        'title': ['AI Engineer', 'ML Engineer', 'Data Scientist'],
        'company': ['Tech Corp', 'AI Startup', 'Big Data Inc'],
        'location': ['Remote', 'San Francisco', 'New York'],
        'link': ['https://example.com/job1', 'https://example.com/job2', 'https://example.com/job3'],
        'scraped_date': ['2025-01-02', '2025-01-02', '2025-01-02']
    })
    
    html = create_html_email(sample_jobs, sample_jobs)
    text = create_plain_text_email(sample_jobs, sample_jobs)
    
    print("HTML Email Preview:")
    print(html[:500] + "...")
    print("\nPlain Text Email Preview:")
    print(text)